apiVersion: v1
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""
items:
# BuildConfig
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: build-docker-puppetserver
    name: build-docker-puppetserver
    namespace: puppetserver
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: docker-puppetserver:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: fabian
        uri: https://github.com/cegeka/docker-puppetserver.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: rhel7:latest
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: _sDPOQMs3dAh5rLqsZyq
      type: GitHub
    - generic:
        secret: X_k8DUO7OfNOvMI5i9BS
      type: Generic
    - type: ConfigChange
    - imageChange:
        lastTriggeredImageID: registry.redhat.io/rhel7@sha256:fa6d586cc22358400a83927fb38c9d9509962ecc9b2c0dad39ffa46fa71cae68
      type: ImageChange
      startTime: 2018-04-20T12:53:21Z
      steps:
      - durationMilliseconds: 1908
        name: PushDockerImage
        startTime: 2018-04-20T12:53:21Z
    startTimestamp: 2018-04-20T12:52:29Z
# Build: to be checked
#- apiVersion: v1
#  kind: Build
#  metadata:
#    labels:
#      app: build-docker-puppetserver
#      buildconfig: build-docker-puppetserver
#      openshift.io/build-config.name: build-docker-puppetserver
#      openshift.io/build.start-policy: Serial
#    name: build-docker-puppetserver
#    namespace: puppetserver
#    ownerReferences:
#    - apiVersion: build.openshift.io/v1
#      controller: true
#      kind: BuildConfig
#      name: docker-puppetserver
#      uid: 0cc15790-4467-11e8-918e-005056821548
#    resourceVersion: "3824584"
#    selfLink: /oapi/v1/namespaces/puppetserver/builds/docker-puppetserver-48
#    uid: 96e6d7f2-449a-11e8-918e-005056821548
#  spec:
#    nodeSelector: null
#    output:
#      pushSecret:
#        name: builder-dockercfg-zwwwp
#      to:
#        kind: ImageStreamTag
#        name: docker-puppetserver:latest
#    postCommit: {}
#    resources: {}
#    revision:
#      git:
#        author:
#          email: thomas@sector7g.be
#          name: Thomas Meeus
#        commit: 1e6b0fbaa6458055920b17b075be917fce8917cb
#        committer:
#          email: thomas@sector7g.be
#          name: Thomas Meeus
#        message: add only ca
#      type: Git
#    serviceAccount: builder
#    source:
#      git:
#        ref: thomas
#        uri: https://github.com/cegeka/docker-puppetserver.git
#      type: Git
#    strategy:
#      dockerStrategy:
#        from:
#          kind: DockerImage
#          name: registry.redhat.io/rhel7@sha256:fa6d586cc22358400a83927fb38c9d9509962ecc9b2c0dad39ffa46fa71cae68
#      type: Docker
#    triggeredBy:
#    - message: Manually triggered
# ImageStream
- apiVersion: v1
  kind: ImageStream
  metadata:
    generation: 1
    labels:
      app: build-docker-puppetserver
    name: build-docker-puppetserver
    namespace: puppetserver
  spec:
    lookupPolicy:
      local: false
# Secret
- apiVersion: v1
  kind: Secret
  metadata:
    name: test-secret
  data:
    username: dmFsdWUtMQ0K
    password: dmFsdWUtMQ0KDQo=
  stringData:
    hostname: myapp.mydomain.com
    secret.properties: |-
      property1=valueA
      property2=valueB
